# coding: utf-8
from sqlalchemy import Column, Float, Integer, Numeric, Text
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class Product(Base):
    __tablename__ = 'products'

    id = Column(Integer, primary_key=True)
    origin = Column(Text)
    is_ocb = Column(Integer)
    package_unit_type = Column(Text)
    secondary_category = Column(Text)
    serving_suggestion = Column(Numeric)
    updated_at = Column(Text)
    price_in_cents = Column(Integer)
    sugar_content = Column(Numeric)
    stock_type = Column(Text)
    inventory_volume_in_milliliters = Column(Integer)
    sugar_in_grams_per_liter = Column(Numeric)
    inventory_count = Column(Integer)
    producer_name = Column(Text)
    is_vqa = Column(Integer)
    primary_category = Column(Text)
    price_per_liter_of_alcohol_in_cents = Column(Integer)
    style = Column(Text)
    has_bonus_reward_miles = Column(Integer)
    is_discontinued = Column(Integer)
    is_dead = Column(Integer)
    package_unit_volume_in_milliliters = Column(Integer)
    inventory_price_in_cents = Column(Integer)
    total_package_units = Column(Integer)
    volume_in_milliliters = Column(Integer)
    limited_time_offer_ends_on = Column(Text)
    product_no = Column(Integer)
    value_added_promotion_description = Column(Numeric)
    image_thumb_url = Column(Text)
    bonus_reward_miles = Column(Integer)
    description = Column(Numeric)
    tags = Column(Text)
    tertiary_category = Column(Text)
    tasting_note = Column(Numeric)
    varietal = Column(Text)
    price_per_liter_in_cents = Column(Integer)
    is_kosher = Column(Integer)
    bonus_reward_miles_ends_on = Column(Numeric)
    clearance_sale_savings_in_cents = Column(Integer)
    alcohol_content = Column(Integer)
    released_on = Column(Numeric)
    has_clearance_sale = Column(Integer)
    name = Column(Text)
    has_value_added_promotion = Column(Integer)
    package = Column(Text)
    has_limited_time_offer = Column(Integer)
    regular_price_in_cents = Column(Integer)
    image_url = Column(Text)
    is_seasonal = Column(Integer)
    page = Column(Integer)
    limited_time_offer_savings_in_cents = Column(Integer)


class Store(Base):
    __tablename__ = 'stores'

    id = Column(Integer, primary_key=True)
    sunday_close = Column(Integer)
    has_tasting_bar = Column(Integer)
    telephone = Column(Text)
    thursday_close = Column(Integer)
    postal_code = Column(Text)
    inventory_volume_in_milliliters = Column(Integer)
    inventory_count = Column(Integer)
    saturday_close = Column(Integer)
    city = Column(Text)
    tuesday_close = Column(Integer)
    is_dead = Column(Integer)
    wednesday_close = Column(Integer)
    has_beer_cold_room = Column(Integer)
    inventory_price_in_cents = Column(Integer)
    saturday_open = Column(Integer)
    has_parking = Column(Integer)
    latitude = Column(Float)
    has_special_occasion_permits = Column(Integer)
    fax = Column(Text)
    tags = Column(Text)
    store_no = Column(Integer)
    sunday_open = Column(Integer)
    updated_at = Column(Text)
    thursday_open = Column(Integer)
    products_count = Column(Integer)
    wednesday_open = Column(Integer)
    has_product_consultant = Column(Integer)
    has_bilingual_services = Column(Integer)
    monday_open = Column(Integer)
    friday_open = Column(Integer)
    name = Column(Text)
    friday_close = Column(Integer)
    tuesday_open = Column(Integer)
    longitude = Column(Float)
    has_wheelchair_accessability = Column(Integer)
    monday_close = Column(Integer)
    has_transit_access = Column(Integer)
    has_vintages_corner = Column(Integer)
    address_line_2 = Column(Text)
    address_line_1 = Column(Text)
